import React from 'react';
interface FormData {
    studentName: string;
    studentNameAadhar: string;
    gender: string;
    dob: string;
    aadharNo: string;
    bloodGroup: string;
    religion: string;
    motherTongue: string;
    customMotherTongue: string;
    socialCategory: string;
    ewsStatus: string;
    cwsnStatus: string;
    fatherName: string;
    motherName: string;
    guardianName: string;
    relationWithGuardian: string;
    fatherQualification: string;
    motherQualification: string;
    fatherOccupation: string;
    motherOccupation: string;
    annualIncome: string;
    session: string;
    class: string;
    section: string;
    rollNo: string;
    house: string;
    secondLanguage: string;
    thirdLanguage: string;
    skillSubject: string;
    subjects: string[];
    previousStatus: string;
    previousClass: string;
    previousSection: string;
    previousRollNo: string;
    academicYear: string;
    medium: string;
    admissionType: string;
    country: string;
    state: string;
    district: string;
    block: string;
    panchayat: string;
    address: string;
    locality: string;
    postOffice: string;
    policeStation: string;
    pinCode: string;
    mobileNumber: string;
    email: string;
    guardianCountry: string;
    guardianState: string;
    guardianDistrict: string;
    guardianBlock: string;
    guardianPanchayat: string;
    guardianAddress: string;
    guardianLocality: string;
    guardianPostOffice: string;
    guardianPoliceStation: string;
    guardianPinCode: string;
    guardianMobile: string;
    guardianEmail: string;
    transportFacility: string;
    hostelFacility: string;
    freeShoes: string;
    freeUniform: string;
    freeBooks: string;
    freeExerciseBook: string;
    rteEducation: string;
    nccParticipation: string;
    busRoute?: string;
    pickupPoint?: string;
    transportMonth?: string;
}
interface FormPreviewProps {
    formData: FormData;
    photoPreview: string | null;
    onEdit: () => void;
    onSubmit: (e: React.FormEvent) => Promise<void>;
    isSubmitting: boolean;
}
export declare function FormPreview({ formData, photoPreview, onEdit, onSubmit, isSubmitting }: FormPreviewProps): import("react/jsx-runtime").JSX.Element;
export {};
